name: Build Java Application and Run Postman Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/test/

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*.jar

  postman_tests_newman:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman Postman tests
        run: >
          newman run 'https://api.getpostman.com/collections/<COLLECTION_ID>?apikey=${{ secrets.POSTMAN_API_KEY }}' 
          -e 'https://api.getpostman.com/environments/<ENVIRONMENT_ID>?apikey=${{ secrets.POSTMAN_API_KEY }}'
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

  automated_api_tests_postman_cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: >
          postman collection run "28231268-859de912-d87f-416d-8077-5930fec3d39a" 
          -e "28231268-97b78c55-c911-460b-9a77-e66b9906d8ce"